name: example_project
framework: torch
training:
  size: [224, 224]
  batch_size: 64
  shuffle: true
  lr: 1e-3
  epochs: 100
  test_size: 0.1
model:
  pretrained_path: null
dataset:
  path: dataset
  num_classes: 2
