name: magface
framework: torch
training:
  size: [112, 112]
  batch_size: 128
  shuffle: true
  lr: 1e-3
  loss:
    l_margin: 0.45
    u_margin: 0.8
    l_a: 10
    u_a: 110
    scale: 64.0
  scheduler:
    factor: 0.1
    patience: 3
    mode: max
  lambda_g: 35
  last_fc_size: 2011
  epochs: 100
  test_size: 0.1
  easy_margin: false
model:
  pretrained_path: null
  out_conv: 64
  dropout: 0.4
  embedding_size: 512
dataset:
  min_faces: 8
  max_faces: 200
  limit_faces: 200
  path: dataset/ids
